version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: elasticsearch_learn
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk_learn
      
volumes:
  elastic_data: {}

networks:
  elk_learn: